### PR TITLE
Vendor `gardener/gardener@1.71.0`

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform vsphere

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency has been updated:
- github.com/gardener/gardener 1.67.1 -> 1.71.0
```

### CODE REVIEW

**Comment by briantopping** [comment]
Thanks @acumino, please squash

**Comment by acumino** [comment]
> Thanks @acumino, please squash

@briantopping you can choose the `squash and merge` option while merging this PR to squash the commits.

**Review by briantopping — APPROVED** [review]

**Comment by briantopping** [comment]
> @briantopping you can choose the squash and merge option while merging this PR to squash the commits.

@acumino In the future, please squash.

**Pull request merged**
