### PR TITLE
Gcve automation updates

### PR DESCRIPTION
**Pull request by briantopping**
Latest changes for GCVE automation

### CODE REVIEW

**Review by tuxgoose — DISMISSED** [review]
LGTM

**Comment by gardener-robot-ci-2** [comment]
This PR proposes changes that would break the pipeline definition:
```
gardener-extension-provider-vsphere-gcve_automation: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/concourse/replicator.py", line 140, in render
    definition_descriptor = self._render(definition_descriptor)
  File "/usr/lib/python3.10/site-packages/concourse/replicator.py", line 184, in _render
    'definition': factory.create_pipeline_definition(),
  File "/usr/lib/python3.10/site-packages/concourse/factory.py", line 108, in create_pipeline_definition
    validator.validate()
  File "/usr/lib/python3.10/site-packages/concourse/validator.py", line 29, in validate
    self._validate_variant(variant)
  File "/usr/lib/python3.10/site-packages/concourse/validator.py", line 34, in _validate_variant
    self._validate_element(variant)
  File "/usr/lib/python3.10/site-packages/concourse/validator.py", line 38, in _validate_element
    self._validate_element(child, parents | {element})
  File "/usr/lib/python3.10/site-packages/concourse/validator.py", line 39, in _validate_element
    element.validate()
  File "/usr/lib/python3.10/site-packages/concourse/model/step.py", line 491, in validate
    raise ModelValidationError(
model.base.ModelValidationError: image reference must contain colon charater:eu.gcr.io/gardener-project/gardener/extensions/vsphere-gcve-tm-run

```

**Comment by gardener-robot-ci-3** [comment]
The pipeline-definition has been fixed.

**Review by tuxgoose — APPROVED** [review]
LGTM

**Review by tuxgoose — APPROVED** [review]
/lgtm

**Comment by briantopping** [comment]
Closing due to some pipeline error for hours and will reopen.

**Pull request closed without merging**
