### PR TITLE
Add gcloud app to GCVE image

### PR DESCRIPTION
**Pull request by briantopping**
Install `gcloud` on gcve image

### CODE REVIEW

**Review by tuxgoose — APPROVED** [review]
LGTM

**Comment by tuxgoose** [comment]
Looks like we need to figure out a different way to install terraform
```
#17 1.161 E: Unable to locate package terraform
#17 ERROR: executor failed running [/bin/sh -c apt-get install terraform -y]: exit code: 100
------
 > [gardener-extension-gcve-tm-run 6/7] RUN apt-get install terraform -y:
------
executor failed running [/bin/sh -c apt-get install terraform -y]: exit code: 100
Traceback (most recent call last):
  File "<string>", line 182, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('docker', '--config', '/tmp/tmp7rey_vfz', 'build', '--progress', 'plain', '--target', 'gardener-extension-gcve-tm-run', '--tag', 'eu.gcr.io/gardener-project/gardener/extensions/vsphere-gcve-tm-run:v0.19.0-dev-97ee8623a4237a5b6daec7812c6d01eefcfa883d', '--file', 'main-image/Dockerfile', 'main-image/')' returned non-zero exit status 1.

```

**Review by tuxgoose — CHANGES_REQUESTED** [review]
need to change the way terraform is installed

**Comment by briantopping** [comment]
That’s an old version of the code. I ended up changing several things to get that fixed (such as moving to Debian 11 for the base image).

Sent from my iPhone

On Sep 9, 2022, at 08:17, Phillip Guzman ***@***.***> wrote:

﻿

Looks like we need to figure out a different way to install terraform

#17 1.161 E: Unable to locate package terraform
#17 ERROR: executor failed running [/bin/sh -c apt-get install terraform -y]: exit code: 100
------
 > [gardener-extension-gcve-tm-run 6/7] RUN apt-get install terraform -y:
------
executor failed running [/bin/sh -c apt-get install terraform -y]: exit code: 100
Traceback (most recent call last):
  File "<string>", line 182, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('docker', '--config', '/tmp/tmp7rey_vfz', 'build', '--progress', 'plain', '--target', 'gardener-extension-gcve-tm-run', '--tag', 'eu.gcr.io/gardener-project/gardener/extensions/vsphere-gcve-tm-run:v0.19.0-dev-97ee8623a4237a5b6daec7812c6d01eefcfa883d', '--file', 'main-image/Dockerfile', 'main-image/')' returned non-zero exit status 1.

**Review by tuxgoose — DISMISSED** [review]

**Comment by tuxgoose** [comment]
Its like there is an old job blocking me from merging, did you rename it?

**Review by tuxgoose — APPROVED** [review]
LGTM

**Pull request merged**
