### PR TITLE
Upgrade golang to 1.19.4, other dependencies as needed

### PR DESCRIPTION
**Pull request by briantopping**
Signed-off-by: Brian Topping <brian.topping@sap.com>

**How to categorize this PR?**

/area security
/kind cleanup
/platform vsphere

**Release note**:

```other operator
Upgrade golang to 1.19.4, other dependencies as needed
```

### CODE REVIEW

**Review by tuxgoose — APPROVED** [review]
lgtm

**Comment by briantopping** [comment]
Looks like I used a name that has protected meaning, closing and reopening on a different branch name

**Pull request closed without merging**
