### PR TITLE
Revendor `gardener/gardener@v1.73`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform vsphere

**What this PR does / why we need it**:
Revendor `gardener/gardener@v1.73`

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Comment by briantopping** [comment]
Still waiting on the availability of a vSphere test endpoint to get this release out.

**Comment by rfranzke** [comment]
Sure, if we wait anyways, perhaps we can get a few more PRs in :)

**Pull request merged**
