### PR TITLE
Recover main branch to status at v0.27.0 release, plus upstream changes

### PR DESCRIPTION
**Pull request by briantopping**
Revert to 0.27 release point

### CODE REVIEW

**Review by marwinski — DISMISSED** [review]

**Comment by MartinWeindel** [comment]
Fixed duplicate env variable `NODEGETINFO_WATCH_TIMEOUT_MINUTES` in DaemonSet `vsphere-csi-node` as it caused hibernation to fail.

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Pull request merged**
