### PR TITLE
Fix the type of the network policy port

### PR DESCRIPTION
**Pull request by istvanballok**
**How to categorize this PR?**

/area networking
/kind bug
/platform vsphere

**What this PR does / why we need it**:

The networking annotations (see [doc][]) of the `cloud-controller-manager` service

```
networking.resources.gardener.cloud/from-all-scrape-targets-allowed-ports: '[{"port":"10258","protocol":"TCP"}]'

networking.resources.gardener.cloud/from-policy-allowed-ports: '[{"port":"10258","protocol":"TCP"}]'
networking.resources.gardener.cloud/from-policy-pod-label-selector: all-scrape-targets
```

contain the port number as a string, as introduced in [PR 411][] and [PR 383][], probably as a typo.

Although a string port can be [parsed][] into the `NetworkPolicyPort` [struct][] which expects an `IntOrString`, the validation of the resulting `NetworkPolicy` in the kubernetes API server [fails][] in the `IsValidPortName` [method][]. If the port is a string, it is expected to be a port name, otherwise it should be a number.

When the validation fails, the generated network policies

```
 egress-to-cloud-controller-manager-tcp-10258-via-all-scrape-targets
ingress-to-cloud-controller-manager-tcp-10258-via-all-scrape-targets
```

can not be created, and hence the control plane Prometheus can not scrape the `cloud-controller-manager` pods, which leads to the `CloudControllerManagerDown` [alerts][].

The fix is to use a number for the port value.

[doc]: https://github.com/gardener/gardener/blob/c0419b0e281afcf590afa08c6e845170ec2962c4/docs/concepts/resource-manager.md#networkpolicy-controller
[PR 411]: https://github.com/gardener/gardener-extension-provider-vsphere/pull/411/files#diff-565227090de1b0d3200de25fe9755ea687560f468cf9e6df76a8d4b7d59361e5R10
[PR 383]: https://github.com/gardener/gardener-extension-provider-vsphere/pull/383/files#diff-565227090de1b0d3200de25fe9755ea687560f468cf9e6df76a8d4b7d59361e5R11
[parsed]: https://github.com/gardener/gardener/blob/c0419b0e281afcf590afa08c6e845170ec2962c4/pkg/resourcemanager/controller/networkpolicy/reconciler.go#L227-L238
[struct]: https://github.com/gardener/gardener/blob/c0419b0e281afcf590afa08c6e845170ec2962c4/vendor/k8s.io/api/networking/v1/types.go#L144-L155
[fails]: https://github.com/kubernetes/kubernetes/blob/e298e92115439916320eed0dee26b7c4d8d9a5f6/pkg/apis/networking/validation/validation.go#L76-L92
[method]: https://github.com/kubernetes/kubernetes/blob/419df231bcb8c926deab4f5c1c1a77c94866bb16/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L334
[alerts]: https://github.com/gardener/gardener-extension-provider-vsphere/blob/5559e6fa80728d9906b2de2f49dc1f0d9b25b2f3/charts/internal/seed-controlplane/charts/vsphere-cloud-controller-manager/templates/configmap-observability.yaml#L43

**Which issue(s) this PR fixes**:
Fixes a "typo" introduced in #411 and #383.

**Special notes for your reviewer**:

/cc @ScheererJ @rickardsjp @briantopping

Similar to https://github.com/gardener/gardener-extension-provider-alicloud/pull/637

Note: I confirmed in an existing dev shoot that the network policies are created as expected if the annotation uses the port number, but I haven't performed an end-to-end test e.g. with the [getting_started_locally_with_extensions.md](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally_with_extensions.md) setup.

**Release note**:

```bugfix operator
A bug related to the network policy annotations that prevented the shoot control plane Prometheus from scraping the `cloud-controller-manager` and caused false alerts is fixed.
```

### CODE REVIEW

**Comment by istvanballok** [comment]
@briantopping Once this PR is reviewed and merged, could you please create a new release of the extension for the next possible cycle so that the fix can reach the Gardener landscapes?

**Comment by briantopping** [comment]
Hi @istvanballok thanks for this PR. Could you do a `make generate` and push?

**Comment by istvanballok** [comment]
> Could you do a make generate and push?

Thank you for the hint, @briantopping! :)
I'm not sure why the `api.md` changed after executing `make generate`.

**Comment by briantopping** [comment]
> I'm not sure why the api.md changed after executing make generate.
I don't see that after `make generate` on my side. I assume you have the [build dependencies](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md#preparing-the-setup) and they are up-to-date?

**Comment by istvanballok** [comment]
> ... and they are up-to-date?

Thank you, I upgraded `go` `1.20.2 -> 1.21.0` and the diff is still generated. I'm not sure what is going on: `make generate` calls `hack/generate.sh` which eventually calls `go generate`, so the output should be consistent when I'm using the latest go version.

**Comment by briantopping** [comment]
Interesting. I upgraded my Golang and ran into the same problem. 

After looking at the generation commands, tried `go install github.com/ahmetb/gen-crd-api-reference-docs`. That worked to eliminate the spurious change.

**Comment by istvanballok** [comment]
Hi @briantopping,

Thank you for looking into it.

> tried go install github.com/ahmetb/gen-crd-api-reference-docs. That worked to eliminate the spurious change.

<details>
<summary>I could not reproduce the expected behavior of make generate for quite some time...</summary>

I figured that this line https://github.com/gardener/gardener-extension-provider-vsphere/blob/88d0081e3a336b3cfb6d5bddc5ae9e81d28ea607/pkg/apis/vsphere/v1alpha1/doc.go#L20

calls `gen-crd-api-reference-docs` and the tool is installed here, https://github.com/gardener/gardener-extension-provider-vsphere/blob/88d0081e3a336b3cfb6d5bddc5ae9e81d28ea607/vendor/github.com/gardener/gardener/hack/tools.mk#L110-L111

_if not already present_ under this path: `hack/tools/bin/gen-crd-api-reference-docs`.

So I hypothesized that maybe you are using an older build of that tool, and I tried the previously vendored versions (v0.1.5, v0.2.0 and v0.3.0) but I consistently got the same behavior.

```
cd pkg/apis/vsphere/v1alpha1/
GOBIN=$(pwd) go install github.com/ahmetb/gen-crd-api-reference-docs # +@ v0.1.5, v0.2.0 and v0.3.0 and master
./gen-crd-api-reference-docs -api-dir . -config ../../../../hack/api-reference/api.json -template-dir ../../../../vendor/github.com/gardener/gardener/hack/api-reference/template -out-file ../../../../hack/api-reference/api.md
```

The map's type is used to be rendered as

```
map[string]github.com/gardener/gardener-extension-provider-vsphere/pkg/apis/vsphere/v1alpha1.ZoneConfig
```

and for me it is rendered as

```
map[string]..ZoneConfig
```

Then I figured `.` stands for the current package, so the tool is referring to the current package with the relative path.

This is the template: https://github.com/gardener/gardener-extension-provider-vsphere/blob/88d0081e3a336b3cfb6d5bddc5ae9e81d28ea607/vendor/github.com/gardener/gardener/hack/api-reference/template/members.tpl#L10-L12

and it calls the `typeDisplayName` function here: https://github.com/gardener/gardener-extension-provider-vsphere/blob/88d0081e3a336b3cfb6d5bddc5ae9e81d28ea607/vendor/github.com/ahmetb/gen-crd-api-reference-docs/main.go#L655

which then yields the name of the map: https://github.com/gardener/gardener-extension-provider-vsphere/blob/88d0081e3a336b3cfb6d5bddc5ae9e81d28ea607/vendor/github.com/ahmetb/gen-crd-api-reference-docs/main.go#L467-L486

but at this point I couldn't quite follow any more.

I also noticed that the `--apidir` flag makes a difference:

```
cd
GOBIN=$(pwd) go install github.com/ahmetb/gen-crd-api-reference-docs
./gen-crd-api-reference-docs -api-dir ./pkg/apis/vsphere/v1alpha1 -config hack/api-reference/api.json -template-dir vendor/github.com/gardener/gardener/hack/api-reference/template/ -out-file hack/api-reference/api.md 
```

yields `map[string]./pkg/apis/vsphere/v1alpha1.ZoneConfig`.

</details>

... until I figured that this depends on the path of the git clone! If the repository is under `~/go/src/github.com/gardener`, then the type is generated as expected.

Then I noticed the recent release, `v0.30.0`, rebased, and calling `make generate` is a no-op now, so I figured that the original diff in `example/controller-registration.yaml` was not related to my PR.

**Comment by MartinWeindel** [comment]
reopen

**Comment by briantopping** [comment]
[like]  Topping, Brian reacted to your message:
________________________________

**Comment by istvanballok** [comment]
The single commit of this PR was unintentionally piggy-backing the unrelated PR https://github.com/gardener/gardener-extension-provider-vsphere/pull/457/commits and it is in the main branch now.
It is fine that that this PR is closed.
I left this message as a clarification that actually this PR is "merged", i.e. the fix is available in the main branch, but the PR state is closed and it will not be mentioned in the release notes either.
However, this simple fix is not so critical so we can leave it like it is. cc @briantopping @MartinWeindel

**Pull request closed without merging**
