### PR TITLE
Support for Kubernetes v1.21

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source usability
/kind enhancement
/priority 3
/platform vsphere
/exp intermediate
/topology garden seed shoot

**What this PR does / why we need it**:
This PR adds support for 1.21 to the extension.

**Which issue(s) this PR fixes**:
Part of gardener/gardener#3851

**Special notes for your reviewer**:
* :white_check_mark: Depends on gardener/gardener#3860
* I have not validated the functionality as follows due to missing test/dev environment:
  * ❔ Create new clusters with versions < 1.21
  * ❔ Create new clusters with version  = 1.21
  * ❔ Upgrade old clusters from version 1.20 to version 1.21
  * ❔ Delete clusters with versions < 1.21
  * ❔ Delete clusters with version  = 1.21

**Release note**:

```feature user
The vSphere extension does now support shoot clusters with Kubernetes version 1.21. You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md) before upgrading to 1.21. 
```

### CODE REVIEW

**Comment by MartinWeindel** [comment]
I have validated the functionality in my test/dev environment:
  * :white_check_mark:  Create new clusters with versions < 1.21
  * :white_check_mark:  Create new clusters with version  = 1.21
  * :white_check_mark:  Upgrade old clusters from version 1.20 to version 1.21
  * :white_check_mark:  Delete clusters with versions < 1.21
  * :white_check_mark:  Delete clusters with version  = 1.21

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Very nice @MartinWeindel, thanks for your support!

**Pull request merged**
