### PR TITLE
Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled 

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform vsphere

**What this PR does / why we need it**:
`PodSecurityPolicy` is deprecated and will be disabled in kubernetes v1.25+.
End-users are provided an option to migrate their PSPs before upgrading and disable the `PodSecurityPolicy` admission plugin in the ShootSpec. 
In that case, we should stop deploying our PSPs as well.

- This PR stops deploying PSPs related to `provider-openstack` if the plugin is disabled in the Shoot.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/5250

**Special notes for your reviewer**:
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/587
/hold
Depends on #294 
/squash 

**Release note**:

```breaking operator
Please make sure you're running gardener@v1.52 or above before upgrading to this version.
```

### CODE REVIEW

**Review by briantopping — COMMENTED** [review]
Thanks, lgtm. Let's hold this until #294 is merged.

/lgtm
/hold

**Review by briantopping — APPROVED** [review]
/lgtm

**Comment by shafeeqes** [comment]
I didn't rebase it. How was it possible to merge?

**Comment by briantopping** [comment]
Not sure, it [did the right thing](https://github.com/gardener/gardener-extension-provider-vsphere/blob/main/charts/gardener-extension-validator-vsphere/charts/runtime/templates/deployment.yaml#L49) though... I assume Github is able to figure out by inferencing on ancestors and action dates what was intended.

**Pull request merged**
