### PR TITLE
Add credential docs

### PR DESCRIPTION
**Pull request by christianhuening**
**How to categorize this PR?**

/area documentation
/kind enhancement
/platform vsphere

**What this PR does / why we need it**:
- add information for required users and roles in vsphere and NSX-T
- 
**Release note**:

```other operator
- add documentation about required vsphere and nsx-t users and permissions
- update documentation for required setting for flatcar support
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @christianhuening for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by briantopping — COMMENTED** [review]
/lgtm

🚀🚀🚀

**Review by briantopping — APPROVED** [review]

**Comment by briantopping** [comment]
@christianhuening Can you remove `gardener/gardener-maintainers` from the reviewers?

**Comment by christianhuening** [comment]
@briantopping Hm I would not know how?! I didn't add them after all.

**Comment by briantopping** [comment]
@christianhuening My bad, it needed a `reviewed/ok-to-test`... Somehow the robot got confused and didn't add it.

**Pull request merged**
