### PR TITLE
added missing fields to vsphere secret

### PR DESCRIPTION
**Pull request by christianhuening**

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @christianhuening for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by MartinWeindel — APPROVED** [review]
/lgtm
Thanks!

**Comment by christianhuening** [comment]
@MartinWeindel there's more i am uncovering (i.e. the guestId stuff for flatcar). do you want an extra MR for that or use this one here?

**Comment by christianhuening** [comment]
also, i found that the documented user role for vcenter is not sufficient (i dont know why yet): https://github.com/gardener/machine-controller-manager-provider-vsphere#recommended-permissions-for-role-of-vsphere-user 

i think this should also be moved into this repo here, what do you think?

**Comment by briantopping** [comment]
Hi @christianhuening Thanks for these contributions! You're welcome to keep bringing the PRs. We can catch up on Slack shortly as well!

**Pull request merged**
